import type { ScenarioMetrics } from "@satyrsmc/shared/client";
import type { LineItem } from "@satyrsmc/shared/client";
import type { Member } from "@satyrsmc/shared/client";

/** Mock scenario metrics for chart stories */
export const mockScenarioMetrics: ScenarioMetrics[] = [
  {
    scenarioKey: "Low",
    ticketPrice: 25,
    staffPrice: 15,
    attendancePercent: 60,
    attendees: 120,
    revenue: 3600,
    totalCosts: 4200,
    totalCostsWithProfitTarget: 4500,
    profit: -600,
    profitVsBreakEven: -600,
    roi: -0.14,
    costPerAttendee: 35,
    profitMargin: -16.7,
    profitPerAttendee: -5,
    avgRevenuePerTicket: 28.8,
    costCoverageRatio: 0.86,
    revenueMixAttendee: 83,
    revenueMixStaff: 12,
    revenueMixDayPass: 5,
    profitTargetCoverage: null,
    breakEvenAttendancePercent: 70,
    breakEvenTotalAttendees: 140,
  },
  {
    scenarioKey: "Mid",
    ticketPrice: 35,
    staffPrice: 20,
    attendancePercent: 75,
    attendees: 150,
    revenue: 5850,
    totalCosts: 4800,
    totalCostsWithProfitTarget: 5200,
    profit: 1050,
    profitVsBreakEven: 1050,
    roi: 0.22,
    costPerAttendee: 32,
    profitMargin: 17.9,
    profitPerAttendee: 7,
    avgRevenuePerTicket: 37.5,
    costCoverageRatio: 1.22,
    revenueMixAttendee: 85,
    revenueMixStaff: 10,
    revenueMixDayPass: 5,
    profitTargetCoverage: 105,
    breakEvenAttendancePercent: 58,
    breakEvenTotalAttendees: 116,
  },
  {
    scenarioKey: "High",
    ticketPrice: 45,
    staffPrice: 25,
    attendancePercent: 90,
    attendees: 180,
    revenue: 9000,
    totalCosts: 5500,
    totalCostsWithProfitTarget: 6000,
    profit: 3500,
    profitVsBreakEven: 3500,
    roi: 0.64,
    costPerAttendee: 30.6,
    profitMargin: 38.9,
    profitPerAttendee: 19.44,
    avgRevenuePerTicket: 45,
    costCoverageRatio: 1.64,
    revenueMixAttendee: 88,
    revenueMixStaff: 8,
    revenueMixDayPass: 4,
    profitTargetCoverage: 116.7,
    breakEvenAttendancePercent: 48,
    breakEvenTotalAttendees: 96,
  },
];

/** Mock line items for cost-by-category chart stories */
export const mockLineItems: LineItem[] = [
  { id: "1", name: "Venue rental", category: "Venue", unitCost: 2000, quantity: 1 },
  {
    id: "2",
    name: "Catering per person",
    category: "Food & Beverage",
    unitCost: 18,
    quantity: 150,
  },
  { id: "3", name: "Sound system", category: "Equipment", unitCost: 500, quantity: 1 },
  { id: "4", name: "Security", category: "Staff & Safety", unitCost: 400, quantity: 2 },
  { id: "5", name: "Marketing", category: "Marketing", unitCost: 300, quantity: 1 },
  { id: "6", name: "Insurance", category: "Admin", unitCost: 250, quantity: 1 },
];

/** Mock members for member card stories */
export const mockMembers: Member[] = [
  {
    id: "1",
    name: "Jane Doe",
    phone_number: "(555) 123-4567",
    email: "jane@example.com",
    address: "123 Main St, City",
    birthday: "1990-05-15",
    member_since: "2020-03",
    is_baby: false,
    position: "Treasurer",
    emergency_contact_name: "John Doe",
    emergency_contact_phone: "(555) 987-6543",
    photo_url: "https://api.dicebear.com/7.x/avataaars/svg?seed=Jane",
    photo_thumbnail_url: "https://api.dicebear.com/7.x/avataaars/svg?seed=Jane",
  },
  {
    id: "2",
    name: "John Smith",
    phone_number: null,
    email: null,
    address: null,
    birthday: null,
    member_since: "2022-06",
    is_baby: false,
    position: "Member",
    emergency_contact_name: null,
    emergency_contact_phone: null,
    photo_url: null,
    photo_thumbnail_url: null,
  },
  {
    id: "3",
    name: "Alex Baby",
    phone_number: null,
    email: null,
    address: null,
    birthday: "2024-01-10",
    member_since: null,
    is_baby: true,
    position: null,
    emergency_contact_name: "Parent",
    emergency_contact_phone: "(555) 111-2222",
    photo_url: null,
    photo_thumbnail_url: null,
  },
];
